### ISSUE TITLE
bug: linux use large page memory, function stubs failed

### ISSUE THREAD

**Issue by github-my** [sinojelly/mockcpp#36]
mprotect for change function head instructions in memory. 
current code use 4K size page, in normal machine should be OK;
but in large page (such as 2M size) mechine, mprotect system call return failed, because memory size not in bound.
so here gives a fix, read page size from kernel config, then set mprotect the right size.
![image](https://user-images.githubusercontent.com/9929992/177672618-25baa581-eb62-4348-9ad4-4f374b6ddb27.png)

**Comment by sinojelly** [comment]
Is it also work on other platforms?
If it's ok, could you open a pull request, so it can help others.
Thanks.
