### ISSUE TITLE
How to returnStringvalue using MOCKER assertion?

### ISSUE THREAD

**Issue by hanishgopi** [sinojelly/mockcpp#38]
Please leave a syntax example to returnStringValue using MOCKER assertion.
if not possible using MOCKER assertion if there is any other way please let me know with a sample example.

**Comment by sinojelly** [comment]
I think maybe you can use return string value mocker like this:
```
    TEST(test_func_mocker)
    {
        MOCKER(Interface::func)
            .expects(once())
            .will(returnValue("OK"));
        ASSERT_EQ("OK", Interface::func());
        GlobalMockObject::verify();
    }
```
