### ISSUE TITLE
while running in linux multi-thread, maybe have coredump 

### ISSUE THREAD

**Issue by github-my** [sinojelly/mockcpp#41]
sample test code:
`#include <stdio.h>
#include <pthread.h>
#include <sys/syscall.h>
#include <unistd.h>
#include "gtest/gtest.h"
#include "mockcpp/mokc.h"

int int_ret_func(int a, int b)
{
    printf("call orginal function %s\n", __FUNCTION__);
    return a + b;
}

int stub_int_ret_func(int a, int b)
{
    int tid = (int)syscall(__NR_gettid);
    printf("call stub function %s, tid: %d\n", __FUNCTION__, tid);
    return a * b;
}

void void_ret_func(int a, int b, int c)
{
    printf("call orginal function %s\n", __FUNCTION__);
}

void stub_void_ret_func(int a, int b, int c)
{
    int tid = (int)syscall(__NR_gettid);
    printf("call stub function %s, tid: %d\n", __FUNCTION__, tid);
}

void *threadFunc(void *arg)
{
    while (1) {
        int ret = int_ret_func(2, 3);
        EXPECT_EQ(ret, 6);
        void_ret_func(2, 3, 4);
        usleep(1000);
    }
    
    return NULL;
}

TEST(TestSuite, Factorial_Stub)
{
    MOCKER(int_ret_func).stubs().will(invoke(stub_int_ret_func));
    MOCKER(void_ret_func).stubs().will(invoke(stub_void_ret_func));
    
    #define TID_CNT 8
    pthread_t tid[TID_CNT];
    for (int loop = 0; loop < TID_CNT; loop++) {
        pthread_create(&tid[loop], NULL, &threadFunc, NULL);
    }
    
    for (int loop = 0; loop < TID_CNT; loop++) {
        pthread_join(tid[loop], NULL);
    }
}`
running result:
![image](https://user-images.githubusercontent.com/9929992/190844855-182b8930-fef2-477f-8b66-b756d535788a.png)

because of data using after free, need to fix

**Comment by github-my** [comment]
MR https://github.com/sinojelly/mockcpp/pull/42  fix it

**Comment by github-my** [comment]
test old testcase result:


[   RUN    ] TestStubContainter::TestStubContainer::testShouldAlwaysReturnAStubBeforeItIsCompleted
[    OK    ] (9 us)
[   RUN    ] TestStubContainter::TestStubContainer::testShouldAlwaysReturnLastStubIfAllStubsHaveBeenReturnedEvenIfItHasBeenCompleted
[    OK    ] (9 us)
[   RUN    ] TestStubContainter::TestStubContainer::testShouldReturnNullIfNoStubWasAdded
[    OK    ] (3 us)
[   RUN    ] TestVirtualTable::TestVirtualTable::shouldBeAbleToConvertToPointerToInterfaceType
[    OK    ] (91 us)
[   RUN    ] TestVirtualTable::TestVirtualTable::shouldThrowExceptionIfTheNumberOfVptrExceedsTheMaxSettingOfConfiguration
[    OK    ] (60 us)
[   RUN    ] TestVirtualTable::TestVirtualTable::shouldBeAbleToSetMethod
[    OK    ] (67 us)
[   RUN    ] TestVirtualTable::TestVirtualTable::shouldThrowExceptionIfAMethodIsNotSet
[    OK    ] (87 us)
[   RUN    ] TestVirtualTable::TestVirtualTable::shouldThrowExceptionIfIndexOfVtblExceedsTheLimitationOfConfiguration
[    OK    ] (65 us)
[   RUN    ] TestVirtualTable::TestVirtualTable::shouldThrowExceptionIfIndexOfVtblExceedsTheNumberOfVptr
[    OK    ] (52 us)
[   RUN    ] TestVirtualTable::TestVirtualTable::shouldBeAbleToGetPreviouslySetIndexInvokableGetterByReturnedPointerToInterface
[    OK    ] (53 us)
[   RUN    ] TestVirtualTable::TestVirtualTable::shouldThrowExceptionIfItExpectedToBeDeletedButActuallyNotWhenItIsVerified
[    OK    ] (52 us)
[   RUN    ] TestVirtualTable::TestVirtualTable::shouldPassVerifyIfThePointerIsDeletedAsExpected
[    OK    ] (44 us)
[   RUN    ] TestVirtualTable::TestVirtualTable::shouldPassVerifyIfThePointerIsNotDeletedAsExpected
[    OK    ] (43 us)
[   RUN    ] TestVirtualTable::TestVirtualTable::shouldFailThrowExceptionWhileTryingToDeleteThePointerWhichWasExpectedNotTo
[    OK    ] (48 us)
[   RUN    ] TestVirtualTable::TestVirtualTable::shouldThrowExceptionIfAnObjectIsExpectedBothKeepAliveAndBeingDelete
[    OK    ] (58 us)
[   RUN    ] TestVirtualTable::TestVirtualTable::shouldThrowExceptionIfAnObjectIsExpectedBothKeepAliveAndBeingDelete2
[    OK    ] (47 us)
[   RUN    ] TestVirtualTable::TestVirtualTable::shouldThrowExceptionWhenTryingToExpectsADeletedObjectKeepAlive
[    OK    ] (55 us)
[   RUN    ] TestVirtualTable::TestVirtualTable::shouldThrowAnExceptionWhenTryingToAccessMethodsOfADeleteObject
[    OK    ] (54 us)


===========================RESULT===========================
[    OK    ] 274 cases from 32 suites ran successfully.

(0s 32116us)
[root@8d528f027148 /sc/01.src/mockcpp]$

**Comment by sinojelly** [comment]
OK, thanks, merged.
